# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy source files and tsconfig
COPY tsconfig.json ./
COPY src ./src

# Build the project
RUN npm run build

# Expose port if necessary (MCP typically uses stdio, so not exposing ports)

# Run the MCP server
CMD [ "node", "./build/index.js" ]
